### ISSUE TITLE
Two of AAAI

### ISSUE THREAD

**Issue by joelxiangnanchen** [Shujian2015/rl4nlp#1]
Zhang et al., 2017 ["Learning Structured Representation for Text Classification via Reinforcement Learning"](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/11/zhang.pdf)

Feng et al., 2017 ["Reinforcement Learning for Relation Classification from Noisy Data"](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/11/AAAI2018Denoising.pdf)

**Comment by Shujian2015** [comment]
Added to the file. Thanks!
